spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/parcel_delivery_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:hamid318}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true